Listar usuarios
jairoD/web-project pull request #2
Opened 2019-10-25 01:48 UTC by tbnicolas

Listar usuarios

2019-10-29 23:56 UTC, jestrade requested changes

2019-10-29 23:56 UTC, jestrade commented on src/components/services/firebase.js
> +export const addUser = (email, name, uid)=>{
dónde se hace el llamado?

2019-10-29 23:56 UTC, jestrade requested changes
no se listan los usuarios

2019-11-01 01:33 UTC, DanielPazB approved these changes

2019-11-01 01:34 UTC, jairoD approved these changes

2019-11-01 01:35 UTC, merged